### ISSUE TITLE
Is there a way to set initial content to the content saved as html before?

### ISSUE THREAD

**Issue by hariprasadiit** [chuckh/polymer-quill#1]
I tried setting html content saved before using same editor as content, but the polymer-quill element is taking the content as plain text and displaying the same.

**Comment by chuckh** [comment]
So you are doing something like this:

 `<polymer-quill content="<h2>Hello World! - Store as HTML</h2>" store-as="html" show-results></polymer-quill>
`

and the editor shows `<h2>Hello World! - Store as HTML</h2>`.

I am working on a fix now.

**Comment by hariprasadiit** [comment]
Thanks for the quick fix. But this fix is not working for delta. `JSON.parse` is throwing errors because of `\n` in the saved delta string. tried escaping it, but it's not solving the issue.

**Comment by chuckh** [comment]
Just pushed a new commit that should fix the `JSON.parse` error.  You can install it by doing:

`bower install polymer-quill#master`

This should handle blank content for working with delta. It should also handle `{"ops":[{"insert":"\n"}]}`.  If your are using `store-as="delta"` your initial data needs to be in that format like below:

```
<h2>Full Toolbar, Show Results, Custom height (150px), Save as Deltas, Save every 1 second</h2>
<polymer-quill content='{"ops":[{"insert":"Hello World! - Store as Delta"},{"attributes":{"header":2},"insert":"\n"}]}'
  class='full'
  store-as="delta"
  save-interval="1000"
  toolbar-type="full"
  show-results>
</polymer-quill>
```

Let me know if this fixes the problem for you.

**Comment by chuckh** [comment]
Just did another release v0.5.0. You can do a bower update to get it. It should address your issue.

**Comment by hariprasadiit** [comment]
yeah, this fix solves blank content issue.

I've found another issue. If we input delta string directly to the content property,like you mentioned in the example above, it's working fine.
but if we store it as a another property like below and do the binding, json parse is throwing errors at the new line chars. Any idea what might be causing this?

`test:{
            type:String,
            value: '{"ops":[{"insert":"Hello World! - Store as Delta"},{"attributes":{"header":2},"insert":"\n"}]}',
            notify: true,
            reflectToAttribute: true
          }`

**Comment by chuckh** [comment]
Are you doing something like this?

```
<polymer-quill content="{{test.value}}"
  store-as="delta"
  show-results>
</polymer-quill>
```

**Comment by hariprasadiit** [comment]
no, like this

`<polymer-quill content="{{test}}"
  store-as="delta"
  show-results>
</polymer-quill>`

**Comment by chuckh** [comment]
Quill is expecting deltas in `{"ops":[{"insert":"Hello World! - Store as Delta"},{"attributes":{"header":2},"insert":"\n"}]}` syntax. It should work if you use `content="{{test.value}}"`, but not `content="{{test}}"`.

You can learn more about Deltas at http://quilljs.com/guides/working-with-deltas/.

**Comment by hariprasadiit** [comment]
`content = "{{test.value}}"` gives undefined, because test is polymer property and it's string type. so when we do the data binding, `content="{{test}}"`, polymer binds the string itself, not the object. but something is happening with `\n` when this binding occurs.

**Comment by hariprasadiit** [comment]
figured out what is causing this.

for polymer property value we need to escape special characters to get it working normally. it seems polymer is processing special chars in the value if we don't escape them.

```
<polymer-quill content="{{test}}" 
store-as="delta" 
show-results> 
</polymer-quill>
```

```
test:{ 
       type:String, 
       value: '{"ops":[{"insert":"Hello World! - Store as Delta"},{"attributes":{"header":2},"insert":"\\n"}]}', 
       notify: true, 
       reflectToAttribute: true 
 }
```

above code works now, after escaping `\n`

**Comment by chuckh** [comment]
Got it.  So if you change `\n` to `\\n` it works!

``` javascript
test: {
  type: String,
  value: '{"ops":[{"insert":"Hello World! - Store as Delta"},{"attributes":{"header":2},"insert":"\\n"}]}',
  notify: true,
  reflectToAttribute: true
}
```

See http://stackoverflow.com/a/42073/2403875 for details.
