### ISSUE TITLE
polymer-quill doesn't work in Shadow DOM

### ISSUE THREAD

**Issue by abdonrd** [chuckh/polymer-quill#10]
You can try:

https://chuckh.github.io/polymer-quill/components/polymer-quill/demo/index.html?dom=shadow

https://chuckh.github.io/polymer-quill/components/polymer-quill/demo/bubble.html?dom=shadow

**Comment by platoscave** [comment]
+1
The funny thing is, I initially get a layout that is messed up (below). When I click on one of the radio buttons it turns back to normal. I'm using chrome v55.

![image](https://cloud.githubusercontent.com/assets/5169566/23283333/9e5c0796-fa25-11e6-9245-fdaed0cf1017.png)

**Comment by chuckh** [comment]
Currently Quilljs does not work with Shadow DOM. Will give it another try with Shadow DOM when porting to Polymer 2.0.

See issue for more information: https://github.com/quilljs/quill/issues/904

**Comment by satyanath** [comment]
I have a working hack. I had to modify both quill and the polymer-quill to get it working. As mentioned this is a hack and definitely not suitable for production use. As I have very little free time I could not do a pull request. I am attaching the files which I modified. If you find the hack suitable you can use it to modify the code and get it working in shadowDom. 

To summarize the changes are as follows

Quill.js

1) Modified to not run the factory function at the beginning and save that function in a variable.
2) Added an argument qComponent to store the component (rather shadowRoot) of the component. 
3) Pass the qComponent to the other objects called where quill is not passed. 
4) Modify the places where document is used (leaving out places where createElement is called) to use qComponent instead.

Polymer-quill

1) Moved to the code from ready routine to attached (this step may not be necessary). 
2) Modified the styles in polymer-quill-styles-snow.html to remove :host and ::content
3) Modified to call the saved factory function first and then call the Quill function. The quill function is now called with the component reference. 

I have used it in my project and it is getting tested along with other things. Please do a diff to find out all the changes. Review and only then include the changes appropriately. 
[pquill.zip](https://github.com/chuckh/polymer-quill/files/957430/pquill.zip)

This can be modified to work both with shady DOM and shadow DOM. I just needed only shadow DOM for my project.

Hope this is of some use.  
[pquill.zip](https://github.com/chuckh/polymer-quill/files/957433/pquill.zip)

**Comment by amhhernandez** [comment]
@satyanath 

Nice mod! It's working!

**Comment by satyanath** [comment]
Thanks. Hope it gets into the main code base.

I had only did it as a hack - so you may have to improve the code before 
you put it in.

Regards,

S.Satyanath

**Comment by Asha-N** [comment]
satyanath sir,
 This hack works only for chrome. How to make it work for IE and firefox ?

This is how it looks on firefox and IE browsers :
![image](https://user-images.githubusercontent.com/28390751/28165237-9ce8120e-67f0-11e7-99f0-4a73ddda70ae.png)

**Comment by satyanath** [comment]
Hi Asha-N,

IE and Firefox do not support Shadow DOM. Hence you cannot use this hack 
there. You will have to modify to code to not apply the hack when you 
detect IE and Firefox.

Hope this helps.

Regards,

S.Satyanath

**Comment by RoshanLakmal** [comment]
For polymer 1 polymer-quill doesn't work in google chrome however it works on Firefox and IE will anyone will be able to help me?

**Comment by abdonrd** [comment]
Closing and old issue.
