### ISSUE TITLE
the hidden block selects are not hiding

### ISSUE THREAD

**Issue by marcus7777** [chuckh/polymer-quill#12]
[link to example](https://open-elements.org/bower_components/pair-production/demo.html#~(*7b9html8*3cstyle6is*3dZcustom-styleZ*3e74-quill.full6*7b7Q-max-height*3a6300px*3b7Q-min-height*3a6100px*3b7*7d*5cn*3c*2fstyle*3e*5cn*3c4-quill6content*3d*27*7bZopsZ*3a*5b*7bZinsertZ*3aZHello6World*216-6Store6as6DeltaZ*7d*2c*7bZattributesZ*3a*7bZheaderZ*3a2*7d*2cZinsertZ*3aZ*5c*5cnZ*7d*5d*7d*277class*3d*27full*277store-as*3dZdeltaZ7save-interval*3dZ1000Z7toolbar-type*3dZfullZ*3e*5cn*3c*2f4-quill*3e5pendencies845pendenciesDemo85sc876676676675scription8svg9*2c9name8svg-back9*2c9color8*23cccccc9*2c9attrsForDemo89*7d~(~'Qee66--4-quill-editor~'Z*5c9~'4eepolymer~'5ee9*2c9de~'6*20~'7ee*5cn*20*20~'8ee9*3a9~'9*22))) thanks chuck, I happy two patch in dom-if instead of the using the hidden attribute. Should I submit that patch? Or is something else going wrong?

**Comment by chuckh** [comment]
Not sure what's going on.  Yes please submit a patch.

**Comment by marcus7777** [comment]
Something in:
iron-flex-layout.html
Fixes it. 

[here](https://open-elements.org/bower_components/pair-production/demo.html#~(*7b.html9*3cpolymer-quill8content*3d*27*7b6.ops5*5b*7b6.insert56.Hello8World*218-8Store8as8Delta6.*7d*2c*7b6.attributes5*7b6.header52*7d*2c6.insert56.66n6.*7d*5d*7d*27*3e6n*3c*2fpolymer-quill*3e7dependencies9polymer*2ciron-flex-layout7dependenciesDemo97desc96n88886n88886n88886n887description9svg7name9e-e7color9*23cccccc7attrsForDemo9.*7d~(~'5ee6.*3a~'6*5c~'7ee.*2c.~'8*20~'9ee.*3a.~'.*22)))

I propose just adding it

**Comment by chuckh** [comment]
@marcus7777  is this still an issue?  If not should we close?

**Comment by chuckh** [comment]
Closing fixed by adding to iron-flex-layout https://github.com/chuckh/polymer-quill/pull/14.  Thanks @marcus7777
