### ISSUE TITLE
Move away from iron-localstorage

### ISSUE THREAD

**Issue by crutchcorn** [chuckh/polymer-quill#20]
According to their [README](https://github.com/PolymerElements/iron-localstorage); `This element is now deprecated`. There should be an active move to port this away from `iron-localstorage` in order to keep maintained dependancies. However, this could be done after the conversation to a 2.0 hybrid element, as there is a `2.0.0` version release before support was dropped

**Comment by chuckh** [comment]
👍

**Comment by chuckh** [comment]
Fixed with pr #29
