### ISSUE TITLE
eature request : ability for user to delete image

### ISSUE THREAD

**Issue by joeblew99** [chuckh/polymer-quill#4]
I cant delete an image that has been added.

Wondering if you had any thoughts on this ?

**Comment by joeblew99** [comment]
my mistake, it does work !!

I just expected to be able to select the image, like a user can select text. 
Maybe that would be useful ?

I assume this would be a feature request to the main quill.js project ?

**Comment by chuckh** [comment]
Yes it would be a request for main quill.js project.
