### ISSUE TITLE
Install dependency problem

### ISSUE THREAD

**Issue by timcsy** [chuckh/polymer-quill#5]
Hello,
I used bower install --save polymer-quill to install polymer-quill, but the quill version 1.0.5 can't be found because it has changed to 1.0.6 and 1.0.5 was disappear. So I wonder how to change the version, thanks.

> bower install --save polymer-quill
> bower cached        https://github.com/chuckh/polymer-quill.git#0.6.0
> bower validate      0.6.0 against https://github.com/chuckh/polymer-quill.git#*
> bower not-cached    https://github.com/quilljs/quill/releases/download/v1.0.5/quill.tar.gz#*
> bower resolve       https://github.com/quilljs/quill/releases/download/v1.0.5/quill.tar.gz#*
> bower download      https://github.com/quilljs/quill/releases/download/v1.0.5/quill.tar.gz
> bower EHTTP         Status code of 404

**Comment by chuckh** [comment]
Fixed by release v0.6.1: https://github.com/chuckh/polymer-quill/releases/tag/v0.6.1.  Try `bower install --save polymer-quill` again and it will use Quill 1.0.6.
