### ISSUE TITLE
Not working on chrome ?

### ISSUE THREAD

**Issue by jpicus** [chuckh/polymer-quill#7]
Unable to make this works on Chrome, whereas it's working fine on Edge !

Just tried the basic example : 

```
        <style is="custom-style">
  polymer-quill.full {
    --polymer-quill-editor-max-height: 600px;
    --polymer-quill-editor-min-height: 200px;
  }
</style>
  <!--      <h2>Full Toolbar, Show Results, Custom height (150px), Save as Deltas, Save every 1 second</h2>
        <polymer-quill
                content='{"ops":[{"insert":"Hello World! - Store as Delta"},{"attributes":{"header":2},"insert":"\n"}]}'
                class="full"
                store-as="delta"
                save-interval="1000"
                toolbar-type="full"
                show-results>
       </polymer-quill>
```

--------------
On Edge : no problem :-)

On Chrome: get an error message(*) AND what's appearing is ...weird

(*)
Uncaught SyntaxError: Unexpected token H in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLElement.<anonymous> (VM997 polymer-quill.html:354)
    at VM884 polymer.html:1357
![quill_chrome](https://cloud.githubusercontent.com/assets/23242386/21540437/4586f600-cdaf-11e6-83cc-fb7fe808080c.jpg)
![quill_edge](https://cloud.githubusercontent.com/assets/23242386/21540442/495a716c-cdaf-11e6-9277-f05447c57fab.jpg)

Here are two screenshot : the first is Chrome render, second one is Edge

**Comment by chuckh** [comment]
Do you have `dom: 'shady'` set in your index.html, like below?  `<polymer-quill>` requires shady DOM to work. 

```
<script>
      window.Polymer = {
        dom: 'shady',
        lazyRegister: true
      };
</script>
```

See https://github.com/chuckh/polymer-quill/blob/master/demo/index.html#L8-L13 for example.

**Comment by jpicus** [comment]
OK, now working ! Thanks

**Comment by jpicus** [comment]
Question: is the API available with polymer-quill  ? (http://quilljs.com/docs/api/)

**Comment by jpicus** [comment]
Forgot that: dumb question
